#ifndef COMMANDRESPONSES_HPP
# define COMMANDRESPONSES_HPP

# define CODE_RPL_WELCOME  1
# define CODE_RPL_YOURHOST  2
# define CODE_RPL_CREATED  3
# define CODE_RPL_MYINFO  4
# define CODE_RPL_CHANNELMODEIS 324
# define CODE_RPL_NOTOPIC 331
# define CODE_RPL_TOPIC 332
# define CODE_RPL_NAMREPLY 353
# define CODE_RPL_ENDOFNAMES 366

/**
 *  ERRORS
*/

# define CODE_ERR_NOSUCHNICK 401
# define CODE_ERR_CANNOTSENDTOCHAN  404
# define CODE_ERR_NORECIPIENT  411
# define CODE_ERR_NOTEXTTOSEND 412
# define CODE_ERR_UNKNOWNCOMMAND  421
# define CODE_ERR_NONICKNAMEGIVEN 431
# define CODE_ERR_NICKNAMEINUSE 433
# define CODE_ERR_NOTREGISTERED 451
# define CODE_ERR_NEEDMOREPARAMS  461
# define CODE_ERR_ALREADYREGISTRED 462
# define CODE_ERR_PASSWDMISMATCH  464


#endif
